### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by user823083** [anders94/public-private-key-demo#26]
Thanks for developing this wonderful tool for understanding and teaching blockchain! Since this second version is not available on your website anymore, I decided to host it myself - which really is straight forward. However, I had to install some additional modules, namely:

- math-interval-parser
- messageformat
- mustache
- sprintf-js

After manually installing them with npm install <missing module>, everything worked like a charm. I guess one could add them to the dependency list? Thanks again for your great work!

**Comment by anders94** [comment]
Thanks - I'll add those.

Separately, I agree it is probably too hard to find (I'll fix that) but I do host this here:
* https://andersbrownworth.com/blockchain/public-private-keys/ 
* https://andersbrownworth.com/blockchain/public-private-keys/keys
