### ISSUE TITLE
The signature is not written red although it's invalid when the sender/receiver is changed

### ISSUE THREAD

**Issue by ndsvw** [anders94/public-private-key-demo#4]
This is a valid example-transaction at /blockchain:
<img width="442" alt="bildschirmfoto 2018-03-23 um 15 10 47" src="https://user-images.githubusercontent.com/21332313/37833791-8774d5be-2eac-11e8-9488-7f19b81ab7e8.png">

When I edit the amount (in $), the signature gets invalid => signature is written red
<img width="441" alt="bildschirmfoto 2018-03-23 um 15 11 00" src="https://user-images.githubusercontent.com/21332313/37833792-87983e8c-2eac-11e8-881f-d7114feb16ab.png">

But when I edit the sender or the reciever instead, the signature should also be invalid and be written red in my opinion (as it's invalid). That's not the case:
<img width="441" alt="bildschirmfoto 2018-03-23 um 15 21 09" src="https://user-images.githubusercontent.com/21332313/37834383-dd4cb546-2ead-11e8-8cb4-eaea0e1a1772.png">

**Comment by anders94** [comment]
Yeah, thanks for bringing this up. There is a known bug in the message signing library used that will take some work to fix. I agree, it causes confusion in the way things are working right now. I'll eventually fix this although my time is short.

**Comment by anders94** [comment]
Thanks for this. I've fixed it in PR https://github.com/anders94/public-private-key-demo/pull/6 which I'll shortly be deploying at https://anders.com/blockchain/public-private-keys/ as well.
