### ISSUE TITLE
What will be happened if I copy a transaction with signature ?

### ISSUE THREAD

**Issue by tuyendev** [anders94/public-private-key-demo#5]
Hi @anders94 .
First of all, I want to say a huge thank for your amazing video. After watching it, I have a question. Could you help me explain it?
Let imagine, after you send me 5$ with a signature. I'll try to duplicate this transaction, the signature is still the same. It means, the transaction is still valid. Now, I get $10 after twice. How can I prevent that action? Thanks so much.

**Comment by anders94** [comment]
Yes, that is an issue with this. The solution is to also require an incrementing sequence number in each transaction so re-broadcasts would be invalid. I should have included that. I was considering re-doing the video to address this and some confusion people have on the inner working of public / private key pairs but have decided to greatly expand on this in another video instead.

**Comment by tuyendev** [comment]
I see. Now, I got everything. Thanks so much.

**Comment by anders94** [comment]
👍
